[package]
name = "richter"
version = "0.1.0"
authors = ["FourOhFour <404.fourohfour@gmail.com>"]

[dependencies]

serde           = "0.9"
serde_derive    = "0.9"
serde_json      = "0.9"

yaml-rust       = "0.3.5"

reqwest         = "0.4.0"
hyper           = "0.10.4"
rustc-serialize = "0.3.22" 
